name: Update League Patch & Vercel Env

on:
  schedule: [{ cron: '0 0 * * *' }] # 매일 자정 실행
  workflow_dispatch:               # 수동 실행도 가능

jobs:
  update-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: patch
        name: Get latest League patch
        uses: marvinscham/get-league-patch@v1.0.0

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Upsert LEAGUE_PATCH env var in Vercel
        run: |
          PATCH_RESULT=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env/LEAGUE_PATCH" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "value": "${{ steps.patch.outputs.patch }}",
            "target": ["production"]
          }')

          if [ "$PATCH_RESULT" = "404" ]; then
            echo "Creating new LEAGUE_PATCH env var..."
            curl -X POST "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "LEAGUE_PATCH",
              "value": "${{ steps.patch.outputs.patch }}",
              "target": ["production"]
            }'
          else
            echo "Updated LEAGUE_PATCH to ${{ steps.patch.outputs.patch }}"
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      # (선택) Vercel 자동 배포
      - name: Trigger Vercel Deploy
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
