name: Update League Patch & Vercel Env

on:
  schedule:
    - cron: '0 3,9,15,21 * * *' # 매일 한국시간 기준 12시/18시/자정/6시 실행 (UTC 기준)
  workflow_dispatch:

jobs:
  update-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get latest League patch
        id: latest
        run: |
          PATCH=$(curl -s https://ddragon.leagueoflegends.com/realms/kr.json | jq -r '.v')
          echo "patch=$PATCH" >> $GITHUB_OUTPUT

      - name: Fetch current patch from Vercel env
        id: current
        run: |
          CURRENT=$(curl -s -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env")

          CURRENT_PATCH=$(echo "$CURRENT" | jq -r '.envs[] | select(.key=="NEXT_PUBLIC_LEAGUE_PATCH") | .value')
          echo "current_patch=$CURRENT_PATCH" >> $GITHUB_OUTPUT

      - name: Check if update is needed
        id: check
        run: |
          echo "Latest: ${{ steps.latest.outputs.patch }}"
          echo "Current: ${{ steps.current.outputs.current_patch }}"
          if [ "${{ steps.latest.outputs.patch }}" != "${{ steps.current.outputs.current_patch }}" ]; then
            echo "need_update=true" >> $GITHUB_OUTPUT
          else
            echo "need_update=false" >> $GITHUB_OUTPUT
          fi

      - name: Update NEXT_PUBLIC_LEAGUE_PATCH env var in Vercel
        if: steps.check.outputs.need_update == 'true'
        run: |
          echo "Updating Vercel env var..."
          curl -X PATCH "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env/NEXT_PUBLIC_LEAGUE_PATCH" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "value": "${{ steps.latest.outputs.patch }}",
            "target": ["production"]
          }'

      - name: Install Vercel CLI
        if: steps.check.outputs.need_update == 'true'
        run: npm install -g vercel

      - name: Trigger Vercel Deploy
        if: steps.check.outputs.need_update == 'true'
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
