name: Update League Patch & Vercel Env

on:
  schedule: [{ cron: '0 3 * * 3' }] # 매주 수요일 한국시간(KST) 정오 실행
  workflow_dispatch:               # 수동 실행도 가능

jobs:
  update-patch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: patch
        name: Get latest League patch
        uses: marvinscham/get-league-patch@v1.0.0

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Upsert NEXT_PUBLIC_LEAGUE_PATCH env var in Vercel
        run: |
          PATCH_RESULT=$(curl -s -o /dev/null -w "%{http_code}" -X PATCH "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env/NEXT_PUBLIC_LEAGUE_PATCH" \
          -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "value": "${{ steps.patch.outputs.patch }}",
            "target": ["production"]
          }')

          if [ "$PATCH_RESULT" = "404" ]; then
            echo "Creating new NEXT_PUBLIC_LEAGUE_PATCH env var..."
            curl -X POST "https://api.vercel.com/v10/projects/${{ secrets.VERCEL_PROJECT_ID }}/env" \
            -H "Authorization: Bearer ${{ secrets.VERCEL_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "key": "NEXT_PUBLIC_LEAGUE_PATCH",
              "value": "${{ steps.patch.outputs.patch }}",
              "target": ["production"],
              "type": "plain"
            }'
          else
            echo "Updated NEXT_PUBLIC_LEAGUE_PATCH to ${{ steps.patch.outputs.patch }}"
          fi
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

      - name: Trigger Vercel Deploy
        run: |
          vercel --prod --yes --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
